/* automatically generated by rust-bindgen 0.72.1 */

pub const AMDSMI_MAX_STRING_LENGTH: u32 = 64;
pub const AMDSMI_GPU_UUID_SIZE: u32 = 38;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum amdsmi_init_flags_t {
    AMDSMI_INIT_ALL_PROCESSORS = 4294967295,
    AMDSMI_INIT_AMD_CPUS = 1,
    AMDSMI_INIT_AMD_GPUS = 2,
    AMDSMI_INIT_NON_AMD_CPUS = 4,
    AMDSMI_INIT_NON_AMD_GPUS = 8,
    AMDSMI_INIT_AMD_APUS = 3,
}
pub type amdsmi_processor_handle = *mut ::std::os::raw::c_void;
pub type amdsmi_socket_handle = *mut ::std::os::raw::c_void;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum processor_type_t {
    AMDSMI_PROCESSOR_TYPE_UNKNOWN = 0,
    AMDSMI_PROCESSOR_TYPE_AMD_GPU = 1,
    AMDSMI_PROCESSOR_TYPE_AMD_CPU = 2,
    AMDSMI_PROCESSOR_TYPE_NON_AMD_GPU = 3,
    AMDSMI_PROCESSOR_TYPE_NON_AMD_CPU = 4,
    AMDSMI_PROCESSOR_TYPE_AMD_CPU_CORE = 5,
    AMDSMI_PROCESSOR_TYPE_AMD_APU = 6,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum amdsmi_status_t {
    AMDSMI_STATUS_SUCCESS = 0,
    AMDSMI_STATUS_INVAL = 1,
    AMDSMI_STATUS_NOT_SUPPORTED = 2,
    AMDSMI_STATUS_NOT_YET_IMPLEMENTED = 3,
    AMDSMI_STATUS_FAIL_LOAD_MODULE = 4,
    AMDSMI_STATUS_FAIL_LOAD_SYMBOL = 5,
    AMDSMI_STATUS_DRM_ERROR = 6,
    AMDSMI_STATUS_API_FAILED = 7,
    AMDSMI_STATUS_TIMEOUT = 8,
    AMDSMI_STATUS_RETRY = 9,
    AMDSMI_STATUS_NO_PERM = 10,
    AMDSMI_STATUS_INTERRUPT = 11,
    AMDSMI_STATUS_IO = 12,
    AMDSMI_STATUS_ADDRESS_FAULT = 13,
    AMDSMI_STATUS_FILE_ERROR = 14,
    AMDSMI_STATUS_OUT_OF_RESOURCES = 15,
    AMDSMI_STATUS_INTERNAL_EXCEPTION = 16,
    AMDSMI_STATUS_INPUT_OUT_OF_BOUNDS = 17,
    AMDSMI_STATUS_INIT_ERROR = 18,
    AMDSMI_STATUS_REFCOUNT_OVERFLOW = 19,
    AMDSMI_STATUS_BUSY = 30,
    AMDSMI_STATUS_NOT_FOUND = 31,
    AMDSMI_STATUS_NOT_INIT = 32,
    AMDSMI_STATUS_NO_SLOT = 33,
    AMDSMI_STATUS_DRIVER_NOT_LOADED = 34,
    AMDSMI_STATUS_NO_DATA = 40,
    AMDSMI_STATUS_INSUFFICIENT_SIZE = 41,
    AMDSMI_STATUS_UNEXPECTED_SIZE = 42,
    AMDSMI_STATUS_UNEXPECTED_DATA = 43,
    AMDSMI_STATUS_NON_AMD_CPU = 44,
    AMDSMI_STATUS_NO_ENERGY_DRV = 45,
    AMDSMI_STATUS_NO_MSR_DRV = 46,
    AMDSMI_STATUS_NO_HSMP_DRV = 47,
    AMDSMI_STATUS_NO_HSMP_SUP = 48,
    AMDSMI_STATUS_NO_HSMP_MSG_SUP = 49,
    AMDSMI_STATUS_HSMP_TIMEOUT = 50,
    AMDSMI_STATUS_NO_DRV = 51,
    AMDSMI_STATUS_FILE_NOT_FOUND = 52,
    AMDSMI_STATUS_ARG_PTR_NULL = 53,
    AMDSMI_STATUS_AMDGPU_RESTART_ERR = 54,
    AMDSMI_STATUS_SETTING_UNAVAILABLE = 55,
    AMDSMI_STATUS_CORRUPTED_EEPROM = 56,
    AMDSMI_STATUS_MAP_ERROR = 4294967294,
    AMDSMI_STATUS_UNKNOWN_ERROR = 4294967295,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_vram_usage_t {
    pub vram_total: u32,
    pub vram_used: u32,
    pub reserved: [u32; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_vram_usage_t"][::std::mem::size_of::<amdsmi_vram_usage_t>() - 16usize];
    ["Alignment of amdsmi_vram_usage_t"][::std::mem::align_of::<amdsmi_vram_usage_t>() - 4usize];
    ["Offset of field: amdsmi_vram_usage_t::vram_total"]
        [::std::mem::offset_of!(amdsmi_vram_usage_t, vram_total) - 0usize];
    ["Offset of field: amdsmi_vram_usage_t::vram_used"]
        [::std::mem::offset_of!(amdsmi_vram_usage_t, vram_used) - 4usize];
    ["Offset of field: amdsmi_vram_usage_t::reserved"]
        [::std::mem::offset_of!(amdsmi_vram_usage_t, reserved) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_board_info_t {
    pub model_number: [::std::os::raw::c_char; 256usize],
    pub product_serial: [::std::os::raw::c_char; 32usize],
    pub fru_id: [::std::os::raw::c_char; 32usize],
    pub product_name: [::std::os::raw::c_char; 256usize],
    pub manufacturer_name: [::std::os::raw::c_char; 64usize],
    pub reserved: [u32; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_board_info_t"][::std::mem::size_of::<amdsmi_board_info_t>() - 768usize];
    ["Alignment of amdsmi_board_info_t"][::std::mem::align_of::<amdsmi_board_info_t>() - 4usize];
    ["Offset of field: amdsmi_board_info_t::model_number"]
        [::std::mem::offset_of!(amdsmi_board_info_t, model_number) - 0usize];
    ["Offset of field: amdsmi_board_info_t::product_serial"]
        [::std::mem::offset_of!(amdsmi_board_info_t, product_serial) - 256usize];
    ["Offset of field: amdsmi_board_info_t::fru_id"]
        [::std::mem::offset_of!(amdsmi_board_info_t, fru_id) - 288usize];
    ["Offset of field: amdsmi_board_info_t::product_name"]
        [::std::mem::offset_of!(amdsmi_board_info_t, product_name) - 320usize];
    ["Offset of field: amdsmi_board_info_t::manufacturer_name"]
        [::std::mem::offset_of!(amdsmi_board_info_t, manufacturer_name) - 576usize];
    ["Offset of field: amdsmi_board_info_t::reserved"]
        [::std::mem::offset_of!(amdsmi_board_info_t, reserved) - 640usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_power_info_t {
    pub current_socket_power: u32,
    pub average_socket_power: u32,
    pub gfx_voltage: u32,
    pub soc_voltage: u32,
    pub mem_voltage: u32,
    pub power_limit: u32,
    pub reserved: [u32; 11usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_power_info_t"][::std::mem::size_of::<amdsmi_power_info_t>() - 68usize];
    ["Alignment of amdsmi_power_info_t"][::std::mem::align_of::<amdsmi_power_info_t>() - 4usize];
    ["Offset of field: amdsmi_power_info_t::current_socket_power"]
        [::std::mem::offset_of!(amdsmi_power_info_t, current_socket_power) - 0usize];
    ["Offset of field: amdsmi_power_info_t::average_socket_power"]
        [::std::mem::offset_of!(amdsmi_power_info_t, average_socket_power) - 4usize];
    ["Offset of field: amdsmi_power_info_t::gfx_voltage"]
        [::std::mem::offset_of!(amdsmi_power_info_t, gfx_voltage) - 8usize];
    ["Offset of field: amdsmi_power_info_t::soc_voltage"]
        [::std::mem::offset_of!(amdsmi_power_info_t, soc_voltage) - 12usize];
    ["Offset of field: amdsmi_power_info_t::mem_voltage"]
        [::std::mem::offset_of!(amdsmi_power_info_t, mem_voltage) - 16usize];
    ["Offset of field: amdsmi_power_info_t::power_limit"]
        [::std::mem::offset_of!(amdsmi_power_info_t, power_limit) - 20usize];
    ["Offset of field: amdsmi_power_info_t::reserved"]
        [::std::mem::offset_of!(amdsmi_power_info_t, reserved) - 24usize];
};
pub type amdsmi_process_handle_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_proc_info_t {
    pub name: [::std::os::raw::c_char; 32usize],
    pub pid: amdsmi_process_handle_t,
    pub mem: u64,
    pub engine_usage: amdsmi_proc_info_t_engine_usage_,
    pub memory_usage: amdsmi_proc_info_t_memory_usage_,
    pub container_name: [::std::os::raw::c_char; 32usize],
    pub reserved: [u32; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_proc_info_t_engine_usage_ {
    pub gfx: u64,
    pub enc: u64,
    pub reserved: [u32; 12usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_proc_info_t_engine_usage_"]
        [::std::mem::size_of::<amdsmi_proc_info_t_engine_usage_>() - 64usize];
    ["Alignment of amdsmi_proc_info_t_engine_usage_"]
        [::std::mem::align_of::<amdsmi_proc_info_t_engine_usage_>() - 8usize];
    ["Offset of field: amdsmi_proc_info_t_engine_usage_::gfx"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_engine_usage_, gfx) - 0usize];
    ["Offset of field: amdsmi_proc_info_t_engine_usage_::enc"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_engine_usage_, enc) - 8usize];
    ["Offset of field: amdsmi_proc_info_t_engine_usage_::reserved"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_engine_usage_, reserved) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_proc_info_t_memory_usage_ {
    pub gtt_mem: u64,
    pub cpu_mem: u64,
    pub vram_mem: u64,
    pub reserved: [u32; 10usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_proc_info_t_memory_usage_"]
        [::std::mem::size_of::<amdsmi_proc_info_t_memory_usage_>() - 64usize];
    ["Alignment of amdsmi_proc_info_t_memory_usage_"]
        [::std::mem::align_of::<amdsmi_proc_info_t_memory_usage_>() - 8usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::gtt_mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, gtt_mem) - 0usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::cpu_mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, cpu_mem) - 8usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::vram_mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, vram_mem) - 16usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::reserved"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, reserved) - 24usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_proc_info_t"][::std::mem::size_of::<amdsmi_proc_info_t>() - 224usize];
    ["Alignment of amdsmi_proc_info_t"][::std::mem::align_of::<amdsmi_proc_info_t>() - 8usize];
    ["Offset of field: amdsmi_proc_info_t::name"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, name) - 0usize];
    ["Offset of field: amdsmi_proc_info_t::pid"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, pid) - 32usize];
    ["Offset of field: amdsmi_proc_info_t::mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, mem) - 40usize];
    ["Offset of field: amdsmi_proc_info_t::engine_usage"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, engine_usage) - 48usize];
    ["Offset of field: amdsmi_proc_info_t::memory_usage"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, memory_usage) - 112usize];
    ["Offset of field: amdsmi_proc_info_t::container_name"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, container_name) - 176usize];
    ["Offset of field: amdsmi_proc_info_t::reserved"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, reserved) - 208usize];
};
impl amdsmi_memory_type_t {
    pub const AMDSMI_MEM_TYPE_VRAM: amdsmi_memory_type_t =
        amdsmi_memory_type_t::AMDSMI_MEM_TYPE_FIRST;
}
impl amdsmi_memory_type_t {
    pub const AMDSMI_MEM_TYPE_LAST: amdsmi_memory_type_t =
        amdsmi_memory_type_t::AMDSMI_MEM_TYPE_GTT;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum amdsmi_memory_type_t {
    AMDSMI_MEM_TYPE_FIRST = 0,
    AMDSMI_MEM_TYPE_VIS_VRAM = 1,
    AMDSMI_MEM_TYPE_GTT = 2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amd_metrics_table_header_t {
    pub structure_size: u16,
    pub format_revision: u8,
    pub content_revision: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amd_metrics_table_header_t"]
        [::std::mem::size_of::<amd_metrics_table_header_t>() - 4usize];
    ["Alignment of amd_metrics_table_header_t"]
        [::std::mem::align_of::<amd_metrics_table_header_t>() - 2usize];
    ["Offset of field: amd_metrics_table_header_t::structure_size"]
        [::std::mem::offset_of!(amd_metrics_table_header_t, structure_size) - 0usize];
    ["Offset of field: amd_metrics_table_header_t::format_revision"]
        [::std::mem::offset_of!(amd_metrics_table_header_t, format_revision) - 2usize];
    ["Offset of field: amd_metrics_table_header_t::content_revision"]
        [::std::mem::offset_of!(amd_metrics_table_header_t, content_revision) - 3usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_gpu_xcp_metrics_t {
    pub gfx_busy_inst: [u32; 8usize],
    pub jpeg_busy: [u16; 32usize],
    pub vcn_busy: [u16; 4usize],
    pub gfx_busy_acc: [u64; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_gpu_xcp_metrics_t"]
        [::std::mem::size_of::<amdsmi_gpu_xcp_metrics_t>() - 168usize];
    ["Alignment of amdsmi_gpu_xcp_metrics_t"]
        [::std::mem::align_of::<amdsmi_gpu_xcp_metrics_t>() - 8usize];
    ["Offset of field: amdsmi_gpu_xcp_metrics_t::gfx_busy_inst"]
        [::std::mem::offset_of!(amdsmi_gpu_xcp_metrics_t, gfx_busy_inst) - 0usize];
    ["Offset of field: amdsmi_gpu_xcp_metrics_t::jpeg_busy"]
        [::std::mem::offset_of!(amdsmi_gpu_xcp_metrics_t, jpeg_busy) - 32usize];
    ["Offset of field: amdsmi_gpu_xcp_metrics_t::vcn_busy"]
        [::std::mem::offset_of!(amdsmi_gpu_xcp_metrics_t, vcn_busy) - 96usize];
    ["Offset of field: amdsmi_gpu_xcp_metrics_t::gfx_busy_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_xcp_metrics_t, gfx_busy_acc) - 104usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_gpu_metrics_t {
    pub common_header: amd_metrics_table_header_t,
    pub temperature_edge: u16,
    pub temperature_hotspot: u16,
    pub temperature_mem: u16,
    pub temperature_vrgfx: u16,
    pub temperature_vrsoc: u16,
    pub temperature_vrmem: u16,
    pub average_gfx_activity: u16,
    pub average_umc_activity: u16,
    pub average_mm_activity: u16,
    pub average_socket_power: u16,
    pub energy_accumulator: u64,
    pub system_clock_counter: u64,
    pub average_gfxclk_frequency: u16,
    pub average_socclk_frequency: u16,
    pub average_uclk_frequency: u16,
    pub average_vclk0_frequency: u16,
    pub average_dclk0_frequency: u16,
    pub average_vclk1_frequency: u16,
    pub average_dclk1_frequency: u16,
    pub current_gfxclk: u16,
    pub current_socclk: u16,
    pub current_uclk: u16,
    pub current_vclk0: u16,
    pub current_dclk0: u16,
    pub current_vclk1: u16,
    pub current_dclk1: u16,
    pub throttle_status: u32,
    pub current_fan_speed: u16,
    pub pcie_link_width: u16,
    pub pcie_link_speed: u16,
    pub gfx_activity_acc: u32,
    pub mem_activity_acc: u32,
    pub temperature_hbm: [u16; 4usize],
    pub firmware_timestamp: u64,
    pub voltage_soc: u16,
    pub voltage_gfx: u16,
    pub voltage_mem: u16,
    pub indep_throttle_status: u64,
    pub current_socket_power: u16,
    pub vcn_activity: [u16; 4usize],
    pub gfxclk_lock_status: u32,
    pub xgmi_link_width: u16,
    pub xgmi_link_speed: u16,
    pub pcie_bandwidth_acc: u64,
    pub pcie_bandwidth_inst: u64,
    pub pcie_l0_to_recov_count_acc: u64,
    pub pcie_replay_count_acc: u64,
    pub pcie_replay_rover_count_acc: u64,
    pub xgmi_read_data_acc: [u64; 8usize],
    pub xgmi_write_data_acc: [u64; 8usize],
    pub current_gfxclks: [u16; 8usize],
    pub current_socclks: [u16; 4usize],
    pub current_vclk0s: [u16; 4usize],
    pub current_dclk0s: [u16; 4usize],
    pub jpeg_activity: [u16; 32usize],
    pub pcie_nak_sent_count_acc: u32,
    pub pcie_nak_rcvd_count_acc: u32,
    pub accumulation_counter: u64,
    pub prochot_residency_acc: u64,
    pub ppt_residency_acc: u64,
    pub socket_thm_residency_acc: u64,
    pub vr_thm_residency_acc: u64,
    pub hbm_thm_residency_acc: u64,
    pub num_partition: u16,
    pub xcp_stats: [amdsmi_gpu_xcp_metrics_t; 8usize],
    pub pcie_lc_perf_other_end_recovery: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_gpu_metrics_t"][::std::mem::size_of::<amdsmi_gpu_metrics_t>() - 1832usize];
    ["Alignment of amdsmi_gpu_metrics_t"][::std::mem::align_of::<amdsmi_gpu_metrics_t>() - 8usize];
    ["Offset of field: amdsmi_gpu_metrics_t::common_header"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, common_header) - 0usize];
    ["Offset of field: amdsmi_gpu_metrics_t::temperature_edge"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, temperature_edge) - 4usize];
    ["Offset of field: amdsmi_gpu_metrics_t::temperature_hotspot"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, temperature_hotspot) - 6usize];
    ["Offset of field: amdsmi_gpu_metrics_t::temperature_mem"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, temperature_mem) - 8usize];
    ["Offset of field: amdsmi_gpu_metrics_t::temperature_vrgfx"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, temperature_vrgfx) - 10usize];
    ["Offset of field: amdsmi_gpu_metrics_t::temperature_vrsoc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, temperature_vrsoc) - 12usize];
    ["Offset of field: amdsmi_gpu_metrics_t::temperature_vrmem"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, temperature_vrmem) - 14usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_gfx_activity"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_gfx_activity) - 16usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_umc_activity"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_umc_activity) - 18usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_mm_activity"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_mm_activity) - 20usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_socket_power"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_socket_power) - 22usize];
    ["Offset of field: amdsmi_gpu_metrics_t::energy_accumulator"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, energy_accumulator) - 24usize];
    ["Offset of field: amdsmi_gpu_metrics_t::system_clock_counter"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, system_clock_counter) - 32usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_gfxclk_frequency"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_gfxclk_frequency) - 40usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_socclk_frequency"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_socclk_frequency) - 42usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_uclk_frequency"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_uclk_frequency) - 44usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_vclk0_frequency"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_vclk0_frequency) - 46usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_dclk0_frequency"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_dclk0_frequency) - 48usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_vclk1_frequency"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_vclk1_frequency) - 50usize];
    ["Offset of field: amdsmi_gpu_metrics_t::average_dclk1_frequency"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, average_dclk1_frequency) - 52usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_gfxclk"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_gfxclk) - 54usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_socclk"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_socclk) - 56usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_uclk"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_uclk) - 58usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_vclk0"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_vclk0) - 60usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_dclk0"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_dclk0) - 62usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_vclk1"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_vclk1) - 64usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_dclk1"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_dclk1) - 66usize];
    ["Offset of field: amdsmi_gpu_metrics_t::throttle_status"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, throttle_status) - 68usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_fan_speed"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_fan_speed) - 72usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_link_width"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_link_width) - 74usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_link_speed"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_link_speed) - 76usize];
    ["Offset of field: amdsmi_gpu_metrics_t::gfx_activity_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, gfx_activity_acc) - 80usize];
    ["Offset of field: amdsmi_gpu_metrics_t::mem_activity_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, mem_activity_acc) - 84usize];
    ["Offset of field: amdsmi_gpu_metrics_t::temperature_hbm"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, temperature_hbm) - 88usize];
    ["Offset of field: amdsmi_gpu_metrics_t::firmware_timestamp"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, firmware_timestamp) - 96usize];
    ["Offset of field: amdsmi_gpu_metrics_t::voltage_soc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, voltage_soc) - 104usize];
    ["Offset of field: amdsmi_gpu_metrics_t::voltage_gfx"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, voltage_gfx) - 106usize];
    ["Offset of field: amdsmi_gpu_metrics_t::voltage_mem"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, voltage_mem) - 108usize];
    ["Offset of field: amdsmi_gpu_metrics_t::indep_throttle_status"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, indep_throttle_status) - 112usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_socket_power"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_socket_power) - 120usize];
    ["Offset of field: amdsmi_gpu_metrics_t::vcn_activity"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, vcn_activity) - 122usize];
    ["Offset of field: amdsmi_gpu_metrics_t::gfxclk_lock_status"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, gfxclk_lock_status) - 132usize];
    ["Offset of field: amdsmi_gpu_metrics_t::xgmi_link_width"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, xgmi_link_width) - 136usize];
    ["Offset of field: amdsmi_gpu_metrics_t::xgmi_link_speed"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, xgmi_link_speed) - 138usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_bandwidth_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_bandwidth_acc) - 144usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_bandwidth_inst"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_bandwidth_inst) - 152usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_l0_to_recov_count_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_l0_to_recov_count_acc) - 160usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_replay_count_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_replay_count_acc) - 168usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_replay_rover_count_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_replay_rover_count_acc) - 176usize];
    ["Offset of field: amdsmi_gpu_metrics_t::xgmi_read_data_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, xgmi_read_data_acc) - 184usize];
    ["Offset of field: amdsmi_gpu_metrics_t::xgmi_write_data_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, xgmi_write_data_acc) - 248usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_gfxclks"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_gfxclks) - 312usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_socclks"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_socclks) - 328usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_vclk0s"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_vclk0s) - 336usize];
    ["Offset of field: amdsmi_gpu_metrics_t::current_dclk0s"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, current_dclk0s) - 344usize];
    ["Offset of field: amdsmi_gpu_metrics_t::jpeg_activity"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, jpeg_activity) - 352usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_nak_sent_count_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_nak_sent_count_acc) - 416usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_nak_rcvd_count_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_nak_rcvd_count_acc) - 420usize];
    ["Offset of field: amdsmi_gpu_metrics_t::accumulation_counter"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, accumulation_counter) - 424usize];
    ["Offset of field: amdsmi_gpu_metrics_t::prochot_residency_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, prochot_residency_acc) - 432usize];
    ["Offset of field: amdsmi_gpu_metrics_t::ppt_residency_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, ppt_residency_acc) - 440usize];
    ["Offset of field: amdsmi_gpu_metrics_t::socket_thm_residency_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, socket_thm_residency_acc) - 448usize];
    ["Offset of field: amdsmi_gpu_metrics_t::vr_thm_residency_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, vr_thm_residency_acc) - 456usize];
    ["Offset of field: amdsmi_gpu_metrics_t::hbm_thm_residency_acc"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, hbm_thm_residency_acc) - 464usize];
    ["Offset of field: amdsmi_gpu_metrics_t::num_partition"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, num_partition) - 472usize];
    ["Offset of field: amdsmi_gpu_metrics_t::xcp_stats"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, xcp_stats) - 480usize];
    ["Offset of field: amdsmi_gpu_metrics_t::pcie_lc_perf_other_end_recovery"]
        [::std::mem::offset_of!(amdsmi_gpu_metrics_t, pcie_lc_perf_other_end_recovery) - 1824usize];
};
unsafe extern "C" {
    pub fn amdsmi_init(init_flags: u64) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_shut_down() -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_socket_handles(
        socket_count: *mut u32,
        socket_handles: *mut amdsmi_socket_handle,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_socket_info(
        socket_handle: amdsmi_socket_handle,
        len: usize,
        name: *mut ::std::os::raw::c_char,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_processor_handles(
        socket_handle: amdsmi_socket_handle,
        processor_count: *mut u32,
        processor_handles: *mut amdsmi_processor_handle,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_energy_count(
        processor_handle: amdsmi_processor_handle,
        energy_accumulator: *mut u64,
        counter_resolution: *mut f32,
        timestamp: *mut u64,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_gpu_memory_usage(
        processor_handle: amdsmi_processor_handle,
        mem_type: amdsmi_memory_type_t,
        used: *mut u64,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_gpu_metrics_info(
        processor_handle: amdsmi_processor_handle,
        pgpu_metrics: *mut amdsmi_gpu_metrics_t,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_gpu_device_uuid(
        processor_handle: amdsmi_processor_handle,
        uuid_length: *mut ::std::os::raw::c_uint,
        uuid: *mut ::std::os::raw::c_char,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_gpu_board_info(
        processor_handle: amdsmi_processor_handle,
        info: *mut amdsmi_board_info_t,
    ) -> amdsmi_status_t;
}
