/* automatically generated by rust-bindgen 0.72.1 */

pub const AMDSMI_MAX_STRING_LENGTH: u32 = 64;
pub const AMDSMI_GPU_UUID_SIZE: u32 = 38;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum amdsmi_init_flags_t {
    AMDSMI_INIT_ALL_PROCESSORS = 4294967295,
    AMDSMI_INIT_AMD_CPUS = 1,
    AMDSMI_INIT_AMD_GPUS = 2,
    AMDSMI_INIT_NON_AMD_CPUS = 4,
    AMDSMI_INIT_NON_AMD_GPUS = 8,
    AMDSMI_INIT_AMD_APUS = 3,
}
pub type amdsmi_processor_handle = *mut ::std::os::raw::c_void;
pub type amdsmi_socket_handle = *mut ::std::os::raw::c_void;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum processor_type_t {
    AMDSMI_PROCESSOR_TYPE_UNKNOWN = 0,
    AMDSMI_PROCESSOR_TYPE_AMD_GPU = 1,
    AMDSMI_PROCESSOR_TYPE_AMD_CPU = 2,
    AMDSMI_PROCESSOR_TYPE_NON_AMD_GPU = 3,
    AMDSMI_PROCESSOR_TYPE_NON_AMD_CPU = 4,
    AMDSMI_PROCESSOR_TYPE_AMD_CPU_CORE = 5,
    AMDSMI_PROCESSOR_TYPE_AMD_APU = 6,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum amdsmi_status_t {
    AMDSMI_STATUS_SUCCESS = 0,
    AMDSMI_STATUS_INVAL = 1,
    AMDSMI_STATUS_NOT_SUPPORTED = 2,
    AMDSMI_STATUS_NOT_YET_IMPLEMENTED = 3,
    AMDSMI_STATUS_FAIL_LOAD_MODULE = 4,
    AMDSMI_STATUS_FAIL_LOAD_SYMBOL = 5,
    AMDSMI_STATUS_DRM_ERROR = 6,
    AMDSMI_STATUS_API_FAILED = 7,
    AMDSMI_STATUS_TIMEOUT = 8,
    AMDSMI_STATUS_RETRY = 9,
    AMDSMI_STATUS_NO_PERM = 10,
    AMDSMI_STATUS_INTERRUPT = 11,
    AMDSMI_STATUS_IO = 12,
    AMDSMI_STATUS_ADDRESS_FAULT = 13,
    AMDSMI_STATUS_FILE_ERROR = 14,
    AMDSMI_STATUS_OUT_OF_RESOURCES = 15,
    AMDSMI_STATUS_INTERNAL_EXCEPTION = 16,
    AMDSMI_STATUS_INPUT_OUT_OF_BOUNDS = 17,
    AMDSMI_STATUS_INIT_ERROR = 18,
    AMDSMI_STATUS_REFCOUNT_OVERFLOW = 19,
    AMDSMI_STATUS_BUSY = 30,
    AMDSMI_STATUS_NOT_FOUND = 31,
    AMDSMI_STATUS_NOT_INIT = 32,
    AMDSMI_STATUS_NO_SLOT = 33,
    AMDSMI_STATUS_DRIVER_NOT_LOADED = 34,
    AMDSMI_STATUS_NO_DATA = 40,
    AMDSMI_STATUS_INSUFFICIENT_SIZE = 41,
    AMDSMI_STATUS_UNEXPECTED_SIZE = 42,
    AMDSMI_STATUS_UNEXPECTED_DATA = 43,
    AMDSMI_STATUS_NON_AMD_CPU = 44,
    AMDSMI_STATUS_NO_ENERGY_DRV = 45,
    AMDSMI_STATUS_NO_MSR_DRV = 46,
    AMDSMI_STATUS_NO_HSMP_DRV = 47,
    AMDSMI_STATUS_NO_HSMP_SUP = 48,
    AMDSMI_STATUS_NO_HSMP_MSG_SUP = 49,
    AMDSMI_STATUS_HSMP_TIMEOUT = 50,
    AMDSMI_STATUS_NO_DRV = 51,
    AMDSMI_STATUS_FILE_NOT_FOUND = 52,
    AMDSMI_STATUS_ARG_PTR_NULL = 53,
    AMDSMI_STATUS_AMDGPU_RESTART_ERR = 54,
    AMDSMI_STATUS_SETTING_UNAVAILABLE = 55,
    AMDSMI_STATUS_CORRUPTED_EEPROM = 56,
    AMDSMI_STATUS_MAP_ERROR = 4294967294,
    AMDSMI_STATUS_UNKNOWN_ERROR = 4294967295,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_board_info_t {
    pub model_number: [::std::os::raw::c_char; 256usize],
    pub product_serial: [::std::os::raw::c_char; 32usize],
    pub fru_id: [::std::os::raw::c_char; 32usize],
    pub product_name: [::std::os::raw::c_char; 256usize],
    pub manufacturer_name: [::std::os::raw::c_char; 64usize],
    pub reserved: [u32; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_board_info_t"][::std::mem::size_of::<amdsmi_board_info_t>() - 768usize];
    ["Alignment of amdsmi_board_info_t"][::std::mem::align_of::<amdsmi_board_info_t>() - 4usize];
    ["Offset of field: amdsmi_board_info_t::model_number"]
        [::std::mem::offset_of!(amdsmi_board_info_t, model_number) - 0usize];
    ["Offset of field: amdsmi_board_info_t::product_serial"]
        [::std::mem::offset_of!(amdsmi_board_info_t, product_serial) - 256usize];
    ["Offset of field: amdsmi_board_info_t::fru_id"]
        [::std::mem::offset_of!(amdsmi_board_info_t, fru_id) - 288usize];
    ["Offset of field: amdsmi_board_info_t::product_name"]
        [::std::mem::offset_of!(amdsmi_board_info_t, product_name) - 320usize];
    ["Offset of field: amdsmi_board_info_t::manufacturer_name"]
        [::std::mem::offset_of!(amdsmi_board_info_t, manufacturer_name) - 576usize];
    ["Offset of field: amdsmi_board_info_t::reserved"]
        [::std::mem::offset_of!(amdsmi_board_info_t, reserved) - 640usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_power_info_t {
    pub current_socket_power: u32,
    pub average_socket_power: u32,
    pub gfx_voltage: u32,
    pub soc_voltage: u32,
    pub mem_voltage: u32,
    pub power_limit: u32,
    pub reserved: [u32; 11usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_power_info_t"][::std::mem::size_of::<amdsmi_power_info_t>() - 68usize];
    ["Alignment of amdsmi_power_info_t"][::std::mem::align_of::<amdsmi_power_info_t>() - 4usize];
    ["Offset of field: amdsmi_power_info_t::current_socket_power"]
        [::std::mem::offset_of!(amdsmi_power_info_t, current_socket_power) - 0usize];
    ["Offset of field: amdsmi_power_info_t::average_socket_power"]
        [::std::mem::offset_of!(amdsmi_power_info_t, average_socket_power) - 4usize];
    ["Offset of field: amdsmi_power_info_t::gfx_voltage"]
        [::std::mem::offset_of!(amdsmi_power_info_t, gfx_voltage) - 8usize];
    ["Offset of field: amdsmi_power_info_t::soc_voltage"]
        [::std::mem::offset_of!(amdsmi_power_info_t, soc_voltage) - 12usize];
    ["Offset of field: amdsmi_power_info_t::mem_voltage"]
        [::std::mem::offset_of!(amdsmi_power_info_t, mem_voltage) - 16usize];
    ["Offset of field: amdsmi_power_info_t::power_limit"]
        [::std::mem::offset_of!(amdsmi_power_info_t, power_limit) - 20usize];
    ["Offset of field: amdsmi_power_info_t::reserved"]
        [::std::mem::offset_of!(amdsmi_power_info_t, reserved) - 24usize];
};
pub type amdsmi_process_handle_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_proc_info_t {
    pub name: [::std::os::raw::c_char; 32usize],
    pub pid: amdsmi_process_handle_t,
    pub mem: u64,
    pub engine_usage: amdsmi_proc_info_t_engine_usage_,
    pub memory_usage: amdsmi_proc_info_t_memory_usage_,
    pub container_name: [::std::os::raw::c_char; 32usize],
    pub reserved: [u32; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_proc_info_t_engine_usage_ {
    pub gfx: u64,
    pub enc: u64,
    pub reserved: [u32; 12usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_proc_info_t_engine_usage_"]
        [::std::mem::size_of::<amdsmi_proc_info_t_engine_usage_>() - 64usize];
    ["Alignment of amdsmi_proc_info_t_engine_usage_"]
        [::std::mem::align_of::<amdsmi_proc_info_t_engine_usage_>() - 8usize];
    ["Offset of field: amdsmi_proc_info_t_engine_usage_::gfx"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_engine_usage_, gfx) - 0usize];
    ["Offset of field: amdsmi_proc_info_t_engine_usage_::enc"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_engine_usage_, enc) - 8usize];
    ["Offset of field: amdsmi_proc_info_t_engine_usage_::reserved"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_engine_usage_, reserved) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdsmi_proc_info_t_memory_usage_ {
    pub gtt_mem: u64,
    pub cpu_mem: u64,
    pub vram_mem: u64,
    pub reserved: [u32; 10usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_proc_info_t_memory_usage_"]
        [::std::mem::size_of::<amdsmi_proc_info_t_memory_usage_>() - 64usize];
    ["Alignment of amdsmi_proc_info_t_memory_usage_"]
        [::std::mem::align_of::<amdsmi_proc_info_t_memory_usage_>() - 8usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::gtt_mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, gtt_mem) - 0usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::cpu_mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, cpu_mem) - 8usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::vram_mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, vram_mem) - 16usize];
    ["Offset of field: amdsmi_proc_info_t_memory_usage_::reserved"]
        [::std::mem::offset_of!(amdsmi_proc_info_t_memory_usage_, reserved) - 24usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdsmi_proc_info_t"][::std::mem::size_of::<amdsmi_proc_info_t>() - 224usize];
    ["Alignment of amdsmi_proc_info_t"][::std::mem::align_of::<amdsmi_proc_info_t>() - 8usize];
    ["Offset of field: amdsmi_proc_info_t::name"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, name) - 0usize];
    ["Offset of field: amdsmi_proc_info_t::pid"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, pid) - 32usize];
    ["Offset of field: amdsmi_proc_info_t::mem"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, mem) - 40usize];
    ["Offset of field: amdsmi_proc_info_t::engine_usage"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, engine_usage) - 48usize];
    ["Offset of field: amdsmi_proc_info_t::memory_usage"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, memory_usage) - 112usize];
    ["Offset of field: amdsmi_proc_info_t::container_name"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, container_name) - 176usize];
    ["Offset of field: amdsmi_proc_info_t::reserved"]
        [::std::mem::offset_of!(amdsmi_proc_info_t, reserved) - 208usize];
};
impl amdsmi_memory_type_t {
    pub const AMDSMI_MEM_TYPE_VRAM: amdsmi_memory_type_t =
        amdsmi_memory_type_t::AMDSMI_MEM_TYPE_FIRST;
}
impl amdsmi_memory_type_t {
    pub const AMDSMI_MEM_TYPE_LAST: amdsmi_memory_type_t =
        amdsmi_memory_type_t::AMDSMI_MEM_TYPE_GTT;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum amdsmi_memory_type_t {
    AMDSMI_MEM_TYPE_FIRST = 0,
    AMDSMI_MEM_TYPE_VIS_VRAM = 1,
    AMDSMI_MEM_TYPE_GTT = 2,
}
unsafe extern "C" {
    pub fn amdsmi_init(init_flags: u64) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_shut_down() -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_socket_handles(
        socket_count: *mut u32,
        socket_handles: *mut amdsmi_socket_handle,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_socket_info(
        socket_handle: amdsmi_socket_handle,
        len: usize,
        name: *mut ::std::os::raw::c_char,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_processor_handles(
        socket_handle: amdsmi_socket_handle,
        processor_count: *mut u32,
        processor_handles: *mut amdsmi_processor_handle,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_energy_count(
        processor_handle: amdsmi_processor_handle,
        energy_accumulator: *mut u64,
        counter_resolution: *mut f32,
        timestamp: *mut u64,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_gpu_memory_usage(
        processor_handle: amdsmi_processor_handle,
        mem_type: amdsmi_memory_type_t,
        used: *mut u64,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_gpu_device_uuid(
        processor_handle: amdsmi_processor_handle,
        uuid_length: *mut ::std::os::raw::c_uint,
        uuid: *mut ::std::os::raw::c_char,
    ) -> amdsmi_status_t;
}
unsafe extern "C" {
    pub fn amdsmi_get_gpu_board_info(
        processor_handle: amdsmi_processor_handle,
        info: *mut amdsmi_board_info_t,
    ) -> amdsmi_status_t;
}
